################################################################
#
# MineAuction plugin config file
#
################################################################

debug: false
lang: "cz" 

mysql:
  host: "localhost"
  port: "3306"
  database: "db"
  user: "User"
  password: "pass"