################################################################
#
# MineAuction plugin config file
#
################################################################

debug: true
lang: "en"


mysql:
  host: "localhost"
  port: "3306"
  database: "mineauction"
  user: "minecraft"
  password: "1234"