name: MineAuction
main: cz.sognus.mineauction.MineAuction
version: ${version.release}.${version.major}.${buildNumber}
author: Sognus
description: --nope--

commands:
  ma:
    description: Main command for this plugin
    aliases: [mineauction, auction, aukce]
    usage: /<command> help